// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using Puppet.Service;
using System.Collections.Generic;
using UnityEngine;
using Puppet.Core.Model;
using Puppet;
namespace Puppet.Service{
[PrefabAttribute(Name = "Prefabs/Dialog/Friend/DialogListFriend", Depth = 7, IsAttachedToCamera = true, IsUIPanel = true)]
public class DialogListFriendView : BaseDialog<DialogListFriend,DialogListFriendView>
{
		#region 
		public UITable tableListFriend;
		public UITexture avatar;
		public UILabel lbUserName,lbChips,lbLevel,lbNumberPlayed,lbWinPercents;
		public GameObject btnChipGift,btnItemGift,btnJoinGame,formInvited,formProfile,btnFacebook ,btnEmail;
        public UIToggle tabInvitedFriend;
		#endregion
		public override void ShowDialog (DialogListFriend data)
		{
			base.ShowDialog (data);

		}
		protected override void OnEnable(){
		
			UIEventListener.Get (btnChipGift).onClick += onSendChip;
			UIEventListener.Get (btnItemGift).onClick += onSendItem;
			UIEventListener.Get (btnJoinGame).onClick += onJoinGame;
            UIEventListener.Get(btnFacebook).onClick += onClickFacebook;
            UIEventListener.Get(btnEmail).onClick += onClickEmail;
            EventDelegate.Add(tabInvitedFriend.onChange, OnSelectInviteFriend);
			base.OnEnable ();
		}

		protected override void OnDisable(){

			UIEventListener.Get (btnChipGift).onClick -= onSendChip;
			UIEventListener.Get (btnItemGift).onClick -= onSendItem;
			UIEventListener.Get (btnJoinGame).onClick -= onJoinGame;
            UIEventListener.Get(btnFacebook).onClick += onClickFacebook;
            UIEventListener.Get(btnEmail).onClick += onClickEmail;
            EventDelegate.Remove(tabInvitedFriend.onChange, OnSelectInviteFriend);
			base.OnDisable ();
		}

        private void onClickEmail(GameObject go)
        {

        }

        private void onClickFacebook(GameObject go)
        {
            PuApp.Instance.RequestInviteApp("Mời bạn tham gia chơi game cùng chúng tôi");
        }

        private void OnSelectInviteFriend()
        {
            if (tabInvitedFriend.value)
            {
                formInvited.SetActive(true);
                formProfile.SetActive(false);
            }
            else
            {
                formInvited.SetActive(false);
                formProfile.SetActive(true);
            }
        }

        private void onClickTabInviteFriend(GameObject go)
        {
        }
		void onSendChip (GameObject go)
		{

		}

		void onSendItem (GameObject go)
		{

		}

		void onJoinGame (GameObject go)
		{

		}

}
	public class DialogListFriend : AbstractDialogData{
		public List<UserInfo> users;
		public DialogListFriend(List<UserInfo> users) : base(){
			this.users = users;
		}
		public override void ShowDialog ()
		{
			DialogListFriendView.Instance.ShowDialog (this);
		}
	}
}

